deploy stage:
  stage: deploy
  tags: 
  - meao
  variables:
    BUCKET_PATH: ${STAGE_BUCKET_PATH}
  only:
    refs:
    - master
    - dp_gitlab_ci
  script: ./bin/ci-mirror.sh

deploy prod:
  stage: deploy
  tags: 
  - meao
  variables:
    BUCKET_PATH: ${PROD_BUCKET_PATH}
  only:
    refs:
    - production
  script: ./bin/ci-mirror.sh
