stage:
  variables:
    BUCKET_PATH: ${STAGE_BUCKET_PATH}
  only:
    refs:
    - master
  script: ./bin/ci-mirror.sh

prod:
  variables:
    BUCKET_PATH: ${PROD_BUCKET_PATH}
  only:
    refs:
    - production
  script: ./bin/ci-mirror.sh
  