netlify:
  type: deploy
  script:
    # Stage
    - curl -X POST -d {} https://api.netlify.com/build_hooks/5c640383f9a5a50176403765
    # Dead Man's Snitch Ping
    - curl https://nosnch.in/d216258591
  only:
    - schedules
