sudo: false
language: python
python:
  - "2.6"
before_install:
  - mysql -e 'create database lumbergh_app character set utf8;'
  - git submodule update --init --recursive
install:
  - pip install -r requirements/dev.txt
script:
  - python manage.py test
